name: exercises
run-name: bm is testing rn
on: [push]
jobs:
  doing-some-exercises:
    runs-on: ubuntu-latest
    steps:
      - name: listing
        uses: actions/checkout@v3
      - run: ls ${{ github.workspace }}/insecure
      

      
 
    
